version: '2.4'

services:
  nginx-cert:
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: nginx-cert
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"    
  jupyterhub:
    env_file: .env
    build:
      context: ./configs
      dockerfile: Dockerfile
      args:
        UNAME: user
        UID: 1000
        GID: 1000
        UPASSWD: password
        JUPYTERHUB_FQDN: ${JUPYTERHUB_FQDN}
    container_name: jupyterhub
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "8000:8000"
      - "22:22"
    command: /usr/bin/supervisord